kind: source
spec:
  name: aws
  path: cloudquery/aws
  registry: cloudquery
  version: "v32.48.3"
  tables: ["aws_ec2_*"]
  destinations: ["postgresql"]
---
kind: destination
spec:
  name: postgresql
  path: cloudquery/postgresql
  registry: cloudquery
  version: "v8.13.0"
  spec:
    connection_string: "postgres://postgres:pass@host.docker.internal:5432/postgres?sslmode=disable"